# Generated by Django 3.0.3 on 2020-07-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('murr_card', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('murr_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='murr_card.MurrCard', verbose_name='Лайки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='murrens', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
